server:
  port: 4399

sakura:
  datasource:
    entityPackage: com.sakura.entity
    name: sakura
    basePackage: com.sakura.mapper
    qualifier: sakuraQualifier
    jdbcInfos:
      url:
      username:
      password:
      initialSize:
      maxActive:
  redis:
    host:
    port:
    password:
    timeout:
    jedisConfig:
      maxActive:
      maxWait:
      maxIdle:
      minIdle:
  web:
    sessionCookieName: SakuraSessionDev
    sessionCookieDomain: aichidoubao.com
    sessionCacheKeyPre: sakura.session
    sessionExpireSeconds: 604800

idGenerator:
  timeBits: 28
  workerBits: 22
  seqBits: 13
  epochStr: 1622875679513