server:
  port: 4398

spring:
  datasource:
    dynamic:
      primary: master
      strict: false
      datasource:
        master:
          url:
          username:
          password:
          initialSize: 5
          maxActive: 20
          basePackage: com.sakura.mapper
          entityPackage: com.sakura.entity
          qualifier: sakuraQualifier
        slave_1:
          url:
          username:
          password:
          initialSize: 5
          maxActive: 20
          basePackage: com.sakura.mapper
          entityPackage: com.sakura.entity.zhgd

sakura:
  redis:
    host:
    port:
    password:
    timeout: 10000
    jedisConfig:
      maxActive: 600
      maxWait: 3000
      maxIdle: 10
      minIdle: 4
  web:
    sessionCookieName: SakuraSessionDev
    sessionCookieDomain: aichidoubao.com
    sessionCacheKeyPre: sakura.session
    sessionExpireSeconds: 604800

idGenerator:
  timeBits: 28
  workerBits: 22
  seqBits: 13
  epochStr: 1622875679513