server:
  port: 4399

sakura:
  datasource:
    entityPackage: com.sakura.entity
    name: sakura
    basePackage: com.sakura.mapper
    qualifier: sakuraQualifier
    jdbcInfos:
      url: jdbc:mysql://rm-bp1jai672vn7r912s1250108m.mysql.rds.aliyuncs.com:3306/sakuratest?allowPublicKeyRetrieval=true
      username: sakura01
      password: sakura01
      initialSize: 10
      maxActive: 20
  redis:
    host: r-bp1jkeju27v565c4nwpd.redis.rds.aliyuncs.com
    port: 6379
    password: Dnic%123
    timeout: 10000
    jedisConfig:
      maxActive: 600
      maxWait: 3000
      maxIdle: 10
      minIdle: 4
  web:
    sessionCookieName: SakuraSessionDev
    sessionCookieDomain: aichidoubao.com
    sessionCacheKeyPre: sakura.session
    sessionExpireSeconds: 604800

idGenerator:
  timeBits: 28
  workerBits: 22
  seqBits: 13
  epochStr: 1622875679513